"""rename product_color to product_color_stock and add stock column

Revision ID: 65c6188c1698
Revises: e2f4a6b8c0d1
Create Date: 2026-04-03 08:37:27.129333

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '65c6188c1698'
down_revision: Union[str, Sequence[str], None] = 'e2f4a6b8c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_color_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'product_id',
        'color_id',
        name='uq_product_color_stocks_product_color',
    )
    )
    op.create_index(
        op.f('ix_product_color_stocks_id'),
        'product_color_stocks',
        ['id'],
        unique=False,
    )
    op.drop_table('product_colors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_colors',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(
        ['color_id'],
        ['colors.id'],
        name='product_colors_color_id_fkey',
    ),
    sa.ForeignKeyConstraint(
        ['product_id'],
        ['products.id'],
        name='product_colors_product_id_fkey',
    ),
    sa.PrimaryKeyConstraint('product_id', 'color_id', name='product_colors_pkey')
    )
    op.drop_index(op.f('ix_product_color_stocks_id'), table_name='product_color_stocks')
    op.drop_table('product_color_stocks')
    # ### end Alembic commands ###
