name: CD Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # How this looks depends heavily on where you host.
      # For example, if hitting a webhook on Render:
      - name: Trigger Render Deploy
        if: env.RENDER_DEPLOY_HOOK_URL != ''
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
